export const TEMPLATE = 'TEMPLATE';
export const TEMPLATE_VNODE = 'TEMPLATE_VNODE';
export const TEMPLATE_COMPONENT = 'TEMPLATE_COMPONENT';
export const TEMPLATE_COMPONENT_STATELESS = 'TEMPLATE_COMPONENT_STATELESS';
export const VNODE = 'VNODE';
export const VTEXT = 'VTEXT';
export const VCOMPONENT = 'VCOMPONENT';
export const VCOMPONENT_STATELESS = 'VCOMPONENT_STATELESS';
